name: Build packages
on:
  push:
    branches: pmaster
  workflow_dispatch:

jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        john_package_name="pdfmium_viewer"
        export TERMUX_BUILDER_IMAGE_NAME=johnel/package-builder
        export CONTAINER_NAME=termux-package-builder-legacy

  :     export NDK="/home/builder/lib/android-ndk"
        sudo ./scripts/run-docker.sh bash -c "sudo ./build-package.sh -o ./output -I -a arm $john_package_name"
    - name: release
      run: |
        echo "done"
        gh release create ${{ github.run_number}}.0.0 ./output/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash

